name: Dockle Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Dockle scan
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t test-container .

     # - name: Dockle scan
     #   uses: ndoell/dockle-action@master
     #   with:
     #    image: 'test-container'
     #    format: 'sarif'
     #    output: 'dockle-image-results.sarif'

     # - name: Dockle Scan
      #  run : |
      #    export DOCKLE_LATEST=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
      #    grep '"tag_name":' | \
      #    sed -E 's/.*"v([^"]+)".*/\1/' \
      #    ) && \
      #    docker run --rm \
      #    -v /var/run/docker.sock:/var/run/docker.sock \
      #    goodwithtech/dockle:v${DOCKLE_LATEST} -f sarif test-container > dockle-image-results.sarif
      
      - name: Dockle Scan
        run : |
          dockle -f sarif -o dockle-image-results.sarif test-container

      - name: Check conents of workspace
        run: |
          ls ${{ github.workspace }}

      - name: Upload Dockle scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'dockle-image-results.sarif'
          #category: 'image'