name: Dockle Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: trivy
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t test-container .

      - name: Dockle scan
        uses: ndoell/dockle-action@master
        with:
         image: test-container
        
      - name: Check conents of workspace
        run: |
          ls ${{ github.workspace }}

      - name: Upload Dockle scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'dockle-image-results.sarif'
          category: 'image'